[package]
name = "my-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rmp-serde = "1.0.0"

[dependencies]
log = "0.4"
thiserror = "1.0"
wapc = "1.0.0"
wasmtime-provider = "1.0.0"
